FROM registry.access.redhat.com/rhel7.4

ENV DOWNLOAD_LINK=http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/server-jre-8u161-linux-x64.tar.gz
RUN curl -b oraclelicense="accept-securebackup-cookie" -o "server-jre-8u161-linux-x64.tar.gz" -L "$DOWNLOAD_LINK"

ENV JAVA_PKG=server-jre-8u*-linux-x64.tar.gz
ENV JAVA_HOME=/usr/java/default

RUN mkdir /usr/java
RUN mkdir /home/java-app

RUN tar -xvzf server-jre-8u*-linux-x64.tar.gz -C /usr/java

RUN export JAVA_DIR=$(ls -1 -d /usr/java/*) && \
    ln -s $JAVA_DIR /usr/java/latest && \
    ln -s $JAVA_DIR /usr/java/default && \
    alternatives --install /usr/bin/java java $JAVA_DIR/bin/java 20000 && \
    alternatives --install /usr/bin/javac javac $JAVA_DIR/bin/javac 20000 && \
    alternatives --install /usr/bin/jar jar $JAVA_DIR/bin/jar 20000


WORKDIR /home/java-app
RUN rm /server-jre-8u*-linux-x64.tar.gz
RUN rm /*.rpm

RUN chgrp -R 0 /var
RUN chmod -R g=u /var
RUN chgrp -R 0 /home
RUN chmod -R g=u /home
