FROM docker-registry.default.svc:5000/sample/java-docker:latest

RUN curl -o "fipscheck.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/fipscheck-1.4.1-6.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "fipscheck.rpm"
RUN curl -o "fipscheck-lib.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/fipscheck-lib-1.4.1-6.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "fipscheck-lib.rpm"
RUN curl -o "groff-base.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/groff-base-1.22.2-8.el7.x86_64.rpm"
RUN rpm -Uvh "groff-base.rpm"
RUN curl -o "less.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/less-458-9.el7.x86_64.rpm"
RUN rpm -Uvh "less.rpm"
RUN curl -o "libedit.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/libedit-3.0-12.20121213cvs.el7.x86_64.rpm"
RUN rpm -Uvh "libedit.rpm"
RUN curl -o "libgnome-keyring.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/libgnome-keyring-3.12.0-1.el7.x86_64.rpm"
RUN rpm -Uvh "libgnome-keyring.rpm"
RUN curl -o "openssh.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/openssh-7.4p1-11.el7.x86_64.rpm"
RUN rpm -Uvh "openssh.rpm"
RUN curl -o "openssh-clients.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/openssh-clients-7.4p1-11.el7.x86_64.rpm"
RUN rpm -Uvh "openssh-clients.rpm"

RUN curl -o "perl-carp.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Carp-1.26-244.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-carp.rpm"
RUN curl -o "perl.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-5.16.3-292.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl.rpm"
RUN curl -o "perl-encode.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Encode-2.51-7.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl-encode.rpm"
RUN curl -o "perl-error.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Error-0.17020-2.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-error.rpm"
RUN curl -o "perl-exporter.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Exporter-5.68-3.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-exporter.rpm"
RUN curl -o "perl-File-Path.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-File-Path-2.09-2.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-File-Path.rpm"
RUN curl -o "perl-File-Temp.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-File-Temp-0.23.01-3.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-File-Temp.rpm"
RUN curl -o "perl-filter.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Filter-1.49-3.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl-filter.rpm"
RUN curl -o "perl-Getopt-Long.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Getopt-Long-2.40-2.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-Getopt-Long.rpm"
RUN curl -o "perl-git.rpm" -L "http://mirror.centos.org/centos/7/updates/x86_64/Packages/perl-Git-1.8.3.1-12.el7_4.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-git.rpm"
RUN curl -o "perl-HTTP-Tiny.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-HTTP-Tiny-0.033-3.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-HTTP-Tiny.rpm"
RUN curl -o "perl-PathTools.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-PathTools-3.40-5.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl-PathTools.rpm"
RUN curl -o "perl-Pod-Escapes.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Pod-Escapes-1.04-292.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-Pod-Escapes.rpm"
RUN curl -o "perl-Pod-Perldoc.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Pod-Perldoc-3.20-4.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-Pod-Perldoc.rpm"
RUN curl -o "perl-Pod-Simple.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Pod-Simple-3.28-4.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-Pod-Simple.rpm"
RUN curl -o "perl-Pod-Usage.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Pod-Usage-1.63-3.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-Pod-Usage.rpm"
RUN curl -o "perl-Scalar-List-Utils.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Scalar-List-Utils-1.27-248.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl-Scalar-List-Utils.rpm"
RUN curl -o "perl-Socket.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Socket-2.010-4.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl-Socket.rpm"
RUN curl -o "perl-TermReadKey.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-TermReadKey-2.30-20.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl-TermReadKey.rpm"
RUN curl -o "perl-Storable.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Storable-2.45-3.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl-Storable.rpm"
RUN curl -o "perl-Text-ParseWords.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Text-ParseWords-3.29-4.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-Text-ParseWords.rpm"
RUN curl -o "perl-Time-HiRes.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Time-HiRes-1.9725-3.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl-Time-HiRes.rpm"
RUN curl -o "perl-constant.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-constant-1.27-2.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-constant.rpm"
RUN curl -o "perl-Time-Local.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Time-Local-1.2300-2.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-Time-Local.rpm"
RUN curl -o "perl-macros.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-macros-5.16.3-292.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl-macros.rpm"
RUN curl -o "perl-libs.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-libs-5.16.3-292.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl-libs.rpm"
RUN curl -o "perl-parent.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-parent-0.225-244.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-parent.rpm"
RUN curl -o "perl-podlators.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-podlators-2.5.1-3.el7.noarch.rpm"
RUN rpm -Uvh --nodeps "perl-podlators.rpm"
RUN curl -o "perl-threads.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-threads-1.87-4.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl-threads.rpm"
RUN curl -o "perl-threads-shared.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-threads-shared-1.43-6.el7.x86_64.rpm"
RUN rpm -Uvh --nodeps "perl-threads-shared.rpm"
RUN curl -o "rsync.rpm" -L "http://mirror.centos.org/centos/7/os/x86_64/Packages/rsync-3.0.9-18.el7.x86_64.rpm"
RUN rpm -Uvh "rsync.rpm"
RUN curl -o "git.rpm" -L "http://mirror.centos.org/centos/7/updates/x86_64/Packages/git-1.8.3.1-12.el7_4.x86_64.rpm"
RUN rpm -Uvh "git.rpm"
RUN rm *.rpm

RUN git clone https://github.com/pocthps/new.git
RUN find ./ -name *.jar -exec cp {} ./root.jar \;
EXPOSE 7000
RUN chmod u+x /home/java-app/root.jar


CMD ["java","-jar","/home/java-app/root.jar"]
