FROM docker-registry.default.svc:5000/sample/java-docker:latest

ARG TOMCAT_MAJOR_VERSION
ARG TOMCAT_MINOR_VERSION
ARG MIRROR="http://mirror.csclub.uwaterloo.ca/apache"

ENV CATALINA_HOME="/usr/local/tomcat" \
    TOMCAT_MAJOR_VERSION=${TOMCAT_MAJOR_VERSION:-8} \
    TOMCAT_MINOR_VERSION=${TOMCAT_MINOR_VERSION:-8.5.29}
ENV PATH="${PATH}:${CATALINA_HOME}/bin"

RUN mkdir -p "${CATALINA_HOME}"

WORKDIR ${CATALINA_HOME}

RUN set -x \
    && curl -L#O "${MIRROR}/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz" \
    && curl -L#O "https://www.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz.sha1" \
    && sha1sum -c "apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz.sha1" \
    && tar -zxf "apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz" \
    && mv "apache-tomcat-${TOMCAT_MINOR_VERSION}/"* . \
    && rmdir "apache-tomcat-${TOMCAT_MINOR_VERSION}" \
    && rm bin/*.bat "apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz" "apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz.sha1"
    
EXPOSE 8080

RUN chgrp -R 0 /usr
RUN chmod -R g=u /usr

CMD ["catalina.sh", "run"]
